name: test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   name: Test
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Test
  #       run: |
  #           bash main.sh test

  sh-checker:
    runs-on: ubuntu-latest
    name: sh-checker
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Run sh-checker
        uses: luizm/action-sh-checker@v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -d -i 4 -sr
        with:
          sh_checker_comment: true
          sh_checker_exclude: "^backup/* ^xiaoyahelper/*"
